### PR TITLE
Rename the parameters of Google Analytics script

### PR DESCRIPTION
**Pull request by shinnn**
`i` `s` `o` `g` `r` `a` `m` -> `J` `S` `i` `n` `f` `o`

================

The code is generated by using [isogram](https://github.com/shinnn/isogram), a well-tested Google Analytics easter egg generator used in:

* [gulpjs.com](http://gulpjs.com/) - `g` `u` `l` `p` `j` `s`
* [Jekyll website](http://jekyllrb.com/) - `j` `e` `k` `y` `l` `L`
* [NODESCHOOL](http://nodeschool.io/) - `s` `c` `h` `o` `O` `l`
* [cssnext website](https://cssnext.github.io/) - `c` `s` `s` `N` `e` `x` `t`
* [and so on](https://github.com/shinnn/isogram/tree/1363db298b1d9c015581094ccbe8de5f2c2ecf7f#websites-using-isogram)

If you prefer other characters, I'll update the commit. For example:

`n` `o` `d` `e` `j` `s`

```js
!function(n,o,d,e,j,s){n.GoogleAnalyticsObject=d;n[d]||(n[d]=function(){
(n[d].q=n[d].q||[]).push(arguments)});n[d].l=+new Date;j=o.createElement(e);
s=o.getElementsByTagName(e)[0];j.src='//www.google-analytics.com/analytics.js';
s.parentNode.insertBefore(j,s)}(window,document,'ga','script');
```

`S` `u` `s` `h` `i`

```js
!function(S,u,s,h,i){S.GoogleAnalyticsObject=s;S[s]||(S[s]=function(){
(S[s].q=S[s].q||[]).push(arguments)});S[s].l=+new Date;h=u.createElement('script');
i=u.scripts[0];h.src='//www.google-analytics.com/analytics.js';
i.parentNode.insertBefore(h,i)}(window,document,'ga');
```

### CODE REVIEW

**Comment by azu** [comment]
@shinnn Is this generated code async?
It seem this generated code lack of async attribute.

This change is may not reasonable. Thanks.

Related: 

- https://mathiasbynens.be/notes/async-analytics-snippet
- https://github.com/h5bp/html5-boilerplate/pull/1660
- https://github.com/h5bp/html5-boilerplate/pull/1696
- https://developers.google.com/analytics/devguides/collection/analyticsjs/advanced#alternativeSnippet

**Comment by shinnn** [comment]
https://github.com/h5bp/html5-boilerplate/issues/1395#issuecomment-19959891

**Comment by azu** [comment]
> You mean you're planning to switch the GA snippet to the alternative?

Simply put "Yes".

I'v create the new pull request https://github.com/jser/jser.github.io/pull/76
Thank you for giving me the opportunity :thought_balloon:

**Comment by shinnn** [comment]
No problem! Thank for reviewing.

**Pull request closed without merging**
